### ISSUE TITLE
Does it run on windows?

### ISSUE THREAD

**Issue by fjflores** [neurosuite/neuroscope#3]
Hi! I am wondering if you guys have tried to run it on windows.

**Comment by FlorianFranzen** [comment]
Yes, it should run fine on Windows. However for newer version of Windows (8 or 10) you might be required you to run Neuroscope in compatibility mode.

If you do not want to build Neuroscope by hand, please check out the [release page](https://github.com/neurosuite/neuroscope/releases) for the latest Windows builds.
